# Generated by Django 4.0.4 on 2022-06-03 11:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to='audio')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('time_sent', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 3, 18, 22, 45, 410491))),
            ],
        ),
        migrations.CreateModel(
            name='HMM_model_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('model_file', models.FileField(upload_to='models')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
