# Generated by Django 4.0.4 on 2022-06-08 08:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='username',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='device_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='time_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 8, 15, 13, 5, 194144)),
        ),
    ]
