# Generated by Django 4.0.4 on 2022-04-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='name',
        ),
    ]
