# Generated by Django 4.0.4 on 2022-06-08 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_audiofile_username_audiofile_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='time_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 8, 15, 14, 10, 239079)),
        ),
    ]
