# Generated by Django 4.0.4 on 2022-06-08 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_audiofile_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='time_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 8, 15, 16, 32, 522576)),
        ),
    ]
