# Generated by Django 4.0.4 on 2022-06-08 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_audiofile_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='time_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 8, 15, 22, 44, 738818)),
        ),
        migrations.DeleteModel(
            name='HMM_model_file',
        ),
    ]
